import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/Nav";
import { ThemeProvider } from "./components/Theme-Provider";
import { Inter } from "next/font/google";
import SessionWrapper from "@/lib/SessionWrapper";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <SessionWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Nav />
            {children}
          </ThemeProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
